Repository YuYoHan/myrealtrip, pull requests merged in 2024-07, with the labels that each got.

#32 Dev
  db/MyRealTrip.sql
  myrealtrip.iml
  src/controller/mainPage/IndexController.java
  src/dto/mainPage/MainBannerDTO.java
  src/dto/mainPage/TravelCardDTO.java
  web/WEB-INF/lib/gson-2.11.0.jar
Labels: Modify

#35 [Feat] 예외처리 기능 구현
  src/exception/airplan/airPlanException.java
  src/exception/answer/AnswerException.java
  src/exception/externalService/ExternalServiceException.java
  src/exception/hotel/HotelException.java
  src/exception/notice/NoticeException.java
  src/exception/pick/PickException.java
  src/exception/question/QuestionException.java
  src/exception/reservation/ReservationException.java
  src/exception/service/OutOfStockException.java
  src/exception/validation/DataValidationExcption.java
Labels: Feat

#40 [Feat] mytrip 기능 구현
  web/app/mytrip/mytrip.jsp
  web/css/mytrip/mytrip.css
Labels: Feat

#44 [Modify] admin 테이블 수정
  db/MyRealTrip.sql
  myrealtrip.iml
Labels: Modify

#60 [Feat]카톡 친추 기능 추가
  web/app/mainPage/event.jsp
Labels: Feat

#67 [Comment] 항공권 주석 추가
  src/config/page/Criteria.java
  src/config/page/PageDTO.java
  src/dao/air/AirDAO.java
  src/service/air/AirSearchService.java
  web/app/air/airMain.jsp
Labels: Comment

#68 [Feat] 호텔 기능 구현
  src/action/hotel/HotelBannerAction.java
  src/controller/hotel/HotelController.java
  src/dao/hotel/HotelDAO.java
  src/dto/hotel/HotelBannerDTO.java
  web/app/hotel/hotel.jsp
  web/app/hotel/hotel_swiper.jsp
Labels: Feat

#69 [Modify] 호텔 & 항공 기능 수정
  db/MyRealTrip.sql
  src/controller/air/AirController.java
  src/dao/air/AirDAO.java
  src/service/air/AirSearchService.java
  src/service/reserve/HotelReserveService.java
  web/WEB-INF/web.xml
  web/app/air/air.jsp
  web/app/air/airMain.jsp
  web/app/hotel/hotel.jsp
  web/app/hotel/hotel_swiper.jsp
  web/css/air/air.css
  web/js/air.js
Labels: Modify

#70 [Add] 숙소 테이블 컬럼 & 데이터 추가
  db/MyRealTrip.sql
  web/WEB-INF/lib/mail-1.4.7.jar
  web/app/reserve/hotelReserves_side.jsp
Labels: Add

#71 [Add] 메인페이지 첫번째 슬라이드 배너 이미지 수정 및 추가
  db/MyRealTrip.sql
  web/app/air/air.jsp
  web/app/air/airMain.jsp
  web/app/mainPage/mainHeader.jsp
  web/css/air/air.css
  web/js/air.js
Labels: Fix

#74 [Fix] 충돌해결
  src/controller/air/AirController.java
  src/service/air/AirSearchService.java
  web/app/air/air.jsp
Labels: Fix, Modify

#81 [Add] 메인페이지 recommendedplace 화면 출력
  db/MyRealTrip.sql
  src/action/mainPage/IndexAction.java
  src/action/reserve/AirReserveAction.java
  src/controller/air/AirController.java
  src/controller/member/MemberController.java
  src/controller/pay/PayController.java
  src/dao/air/AirCodeDAO.java
  src/dao/air/AirDAO.java
  src/dao/mainPage/MainDAO.java
  src/dao/member/MemberDAO.java
  src/dto/air/AirCodeDTO.java
  src/dto/air/CombinedFlightDTO.java
  src/dto/air/InternationalOperation.java
  src/dto/mainPage/RePlaceDTO.java
  src/service/air/AirSearchService.java
  src/service/member/SignInService.java
  src/service/member/SignUpService.java
  src/service/reserve/AirPayService.java
  src/service/reserve/AirReserveService.java
  src/util/XMLUtility.java
  web/WEB-INF/lib/taglibs-standard-compat-1.2.5.jar
  web/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar
  web/WEB-INF/lib/taglibs-standard-jstlel-1.2.5.jar
  web/WEB-INF/lib/taglibs-standard-spec-1.2.5.jar
  web/WEB-INF/web.xml
  web/app/air/airList.jsp
  web/app/global/header.jsp
  web/app/mainPage/mainPage.jsp
  web/app/mainPage/rePlace.jsp
  web/app/member/signIn_form.jsp
  web/app/member/signUp_form.jsp
  web/app/reserve/airRerserves_side.jsp
  web/app/reserve/airReserves.jsp
  web/css/air/airReserve.css
  web/css/mainPage/mainInfo.css
  web/css/mainPage/replace.css
  web/img/etc/kakaoPay.png
  web/js/payment.js
  web/js/sign_in_form.js
  web/js/tossPayment.js
Labels: Add

#82 [Modify] 카카오 결제 수정
  db/MyRealTrip.sql
  src/action/mainPage/IndexAction.java
  src/service/member/SignInService.java
  web/app/reserve/airRerserves_side.jsp
  web/app/reserve/airReserves.jsp
  web/css/reserve/reserves.css
  web/js/payment.js
Labels: Modify

#84 [Modify] 토스 코드 수정
  .gitignore
  db/MyRealTrip.sql
  myrealtrip1.iml
  src/action/air/AirNoticeListAction.java
  src/config/jdbc/JDBCConfig.java
  src/config/page/Criteria.java
  src/config/page/PageDTO.java
  src/dao/air/AirNoticesDAO.java
  src/dao/mainPage/MainDAO.java
  src/dao/pay/PaymentDAO.java
  src/dto/air/AirPayDTO.java
  src/dto/air/AirplaneReservationsDTO.java
  src/dto/air/AirplanesDTO.java
  src/dto/air/OperationsDTO.java
  src/dto/mainPage/MainDetailDTO.java
  web/app/air/airMain.jsp
  web/app/air/airNoticeList.jsp
  web/app/mainPage/detail.jsp
  web/app/mainPage/mainBanner.jsp
  web/app/mainPage/mainPage.jsp
  web/app/mainPage/rePlace.jsp
  web/css/air/airReserve2.css
  web/css/index.css
  web/img/mainPage/place1.png
  web/img/mainPage/place10.png
  web/img/mainPage/place11.png
  web/img/mainPage/place12.png
  web/img/mainPage/place13.png
  web/img/mainPage/place14.png
  web/img/mainPage/place15.png
  web/img/mainPage/place16.png
  web/img/mainPage/place17.png
  web/img/mainPage/place18.png
  web/img/mainPage/place19.png
  web/img/mainPage/place2.png
  web/img/mainPage/place20.png
  web/img/mainPage/place21.png
  web/img/mainPage/place22.png
  web/img/mainPage/place23.png
  web/img/mainPage/place24.png
  web/img/mainPage/place3.png
  web/img/mainPage/place4.png
  web/img/mainPage/place5.png
  web/img/mainPage/place6.png
  web/img/mainPage/place7.png
  web/img/mainPage/place8.png
  web/img/mainPage/place9.png
  web/js/payment.js
  web/js/tossPayment.js
Labels: Modify

#86 [Fix] JDBCConfig 비번
  src/action/reserve/AirReserveAction.java
  src/config/jdbc/JDBCConfig.java
Labels: Fix

#93 Dev
  db/MyRealTrip.sql
  myrealtrip.iml
  src/action/hotel/HotelBannerAction.java
  src/action/hotel/HotelDetailAction.java
  src/action/reserve/AirReserveAction.java
  src/dao/hotel/HotelDAO.java
  src/dao/pay/PaymentDAO.java
  src/dto/air/AirplaneReservationsDTO.java
  src/dto/hotel/HotelDetailDTO.java
  src/dto/hotel/HotelListDTO.java
  src/service/air/AirSearchService.java
  src/service/member/SignInService.java
  src/service/reserve/AirPayService.java
  web/app/air/airList.jsp
  web/app/hotel/hotel.jsp
  web/app/hotel/hotel_detail.jsp
  web/app/hotel/hotel_swiper.jsp
  web/app/mainPage/mainPage.jsp
  web/app/reserve/airRerserves_side.jsp
  web/app/reserve/airReserves.jsp
  web/css/hotel/hotel.css
  web/css/hotel/hotelDetail.css
  web/js/payment.js
Labels: Add, Fix

#101 [Add] 검색 결과 구현 및 구글 로그인 구현
  myrealtrip.iml
  src/action/hotel/HotelSearchAction.java
  web/app/hotel/hotel.jsp
  web/css/hotel/hotel.css
Labels: Feat, Add

#99 [Add] 검색 기능 추가
  db/MyRealTrip.sql
  src/action/search/SearchAction.java
  src/config/search/SearchConfig.java
  src/config/search/SearchDTO.java
  src/controller/member/SocialLoginController.java
  src/controller/search/SearchController.java
  web/WEB-INF/web.xml
  web/app/global/header.jsp
  web/app/insurance/insurance.jsp
  web/app/insurance/insuranceForm.jsp
  web/app/mainPage/mainPage.jsp
  web/app/member/signIn.jsp
  web/app/member/signUp.jsp
  web/app/search/result.jsp
  web/css/insurance/insurance.css
  web/css/member/sign.css
  web/css/search/result.css
  web/img/member/facebook_log.svg
  web/img/member/facebook_log_on.svg
  web/img/member/google_log.png
  web/img/member/google_log_on.svg
  web/js/loginEffect.js
  web/js/search.js
Labels: Add

#105 [Add] 내 여행 페이지 생성
  src/action/mytrip/MyTripAction.java
  src/controller/mytrip/MyTripController.java
  src/dao/mytrip/MytripDAO.java
  src/dto/mytrip/MyTripRoomDTO.java
  web/WEB-INF/web.xml
  web/app/mytrip/mytrip.jsp
Labels: Add

#106 [Modify] 보험 코드 수정
  target/classes/service/reserve/HotelReserveService.class
  web/app/insurance/insuranceForm.jsp
  web/css/insurance/insurance.css
  web/js/insurance.js
Labels: Modify

#107 [Fix] 메인페이지 수정완료
  .gitignore
  db/MyRealTrip.sql
  myrealtrip.iml
  src/dao/mainPage/MainDAO.java
  src/dto/mainPage/CardDetailDTO.java
  web/app/air/airBanner.jsp
  web/app/air/airMain.jsp
  web/app/mainPage/cardDetail.jsp
  web/app/mainPage/mainDetail.jsp
  web/app/mainPage/mainHeader.jsp
  web/css/air/airBanner.css
  web/css/mainPage/mainDetail.css
Labels: Fix
